# Generated by Django 3.2.7 on 2021-10-08 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='An item type e.g. Publication, Proceedings, Presentation etc.', max_length=50)),
                ('title', models.TextField(default='', help_text='An item title as it should appear on the web.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='The position of this type in the list.')),
                ('decor', models.CharField(default='', help_text='An item decoration unicode symbol.', max_length=25)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(help_text='A brief description of the reference', max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, default=1970, null=True)),
                ('upload', models.FileField(blank=True, default='', null=True, upload_to='static/')),
                ('exturl', models.URLField(blank=True, default='', null=True)),
                ('itype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.referencetype')),
            ],
            options={
                'ordering': ['title', '-year'],
            },
        ),
    ]
